services:
  - type: web
    name: missing-personportal-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn model.app:app --host 0.0.0.0 --port $PORT
